export const CROP_TYPES = [
  "Apple",
  "Apricot",
  "Blackberry",
  "Blackcurrant",
  "Blueberry",
  "Cherry (sour)",
  "Cherry (sweet)",
  "Elderberry",
  "Fig",
  "Gooseberry",
  "Grape (table)",
  "Grape (wine)",
  "Hazelnut",
  "Nectarine",
  "Peach",
  "Pear",
  "Plum",
  "Quince",
  "Raspberry",
  "Redcurrant",
  "Strawberry",
  "Walnut",
];
